/* eslint-disable @next/next/no-before-interactive-script-outside-document */
import { NextPage } from "next";
import type { AppProps } from "next/app";
import Head from "next/head";
import Script from "next/script";
import { ReactElement, ReactNode, useEffect } from "react";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import toast from "../components/Toast";
import "../styles/globals.css";

export type NextPageWithLayout<P = {}, IP = P> = NextPage<P, IP> & {
  getLayout?: (page: ReactElement) => ReactNode;
};

type AppPropsWithLayout = AppProps & {
  Component: NextPageWithLayout;
};

function MyApp({ Component, pageProps }: AppPropsWithLayout) {
  // useEffect(() => {
  //   toast({ type: "info", message: "Hello world!", title: "Title" });
  //   toast({ type: "success", message: "Hello world!" });
  //   toast({
  //     type: "warning",
  //     message: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  //     title: "Custom title",
  //   });
  //   toast({ type: "error", message: "[Error]: Hello world!" });
  // }, []);

  const getLayout = Component.getLayout ?? ((page) => page);

  return (
    <>
      <Head>
        <title>Travel Planner</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Script src='/theme.js' strategy='beforeInteractive' />
      {getLayout(<Component {...pageProps} />)}
      <ToastContainer
        position='top-right'
        autoClose={3000}
        hideProgressBar={false}
        newestOnTop={false}
        draggable={false}
        closeOnClick
        pauseOnHover
      />
    </>
  );
}

export default MyApp;
