import type { NextPage } from "next";
import Head from "next/head";
import Footer from "../components/Footer/Footer";
import Header from "../components/Header/Header";
import Main from "../components/Main/Main";

const Home: NextPage = () => {
  return (
    <div
      id='app'
      className='flex flex-col min-h-screen overflow-hidden bg-white text-charcoal dark:bg-slate-700 dark:text-gainsboro'
    >
      <Head>
        <title>Travel Planner</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* application */}
      <Header />
      <Main />
      <Footer />
    </div>
  );
};

export default Home;
